name = "LazyDecayAngles"
uuid = "1d606af4-d0f8-4ff7-bc8d-eb3f657b7647"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.1.0"

[deps]
FourVectors = "b122eb78-8380-428a-b8c8-584a022ae8b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
FourVectors = ">=0.3.1"
LinearAlgebra = "1"
Test = "1"
julia = "1.10"
